config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  get 'photos/index'

  get 'photos/create'

  get 'photos/new'

  get 'photos/show'

resources :photos




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    	has_attached_file :photo,
		styles: {large: "500x500>", medium: "300x300>", thumb: "100x100>"},
		default_url: "/images/:style/missing.png"

	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new photo_params
    @photo.save
    if @photo.save
      redirect_to photos_index_path
    else
     redirect_to photos_new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<div class="container">
    <div class="jumbotron">
       <div class="text-center">
         <h1 class="display-4">Photo Demo App</h1>
        <p class="lead">Cuz you know I had to do it to em</p>
        <%= button_to('Add a new photo', photos_new_path, :method => :get, :class => 'btn btn-large btn-primary center-block')  %>
       </div>

    </div>
  <div class="row">
    <% @photos.each do |p| %>
   <div class="card col-lg-3 text-center" style="width: 20rem; margin: 20px">
    <%= link_to image_tag(p.photo.url(:medium), style: "margin: 20px 0px;", class: "card-img-top"), photo_path(p.id) %>
    <div class="card-body">
        <h1 class="card-title"><%= p.title %></h1>
        <p class="card-text"><%= p.description %></p>
    </div>
   </div>
 <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
<%= form_for @photo do |f|%>
 <div class="form-group">
    <label for="title"> Photo Title</label>
    <%= f.text_field(:title, {placeholder: "Title of photo", id: "title", class: "form-control"}) %>
  </div>
  <div class="form-group">
    <label for="description">Photo description</label>
    <%= f.text_field(:description, {placeholder: "Description of photo", id: "description", class: "form-control"}) %>
  </div>

  <div class="form-group">
    <label for="file_field">Choose a file</label>
    <%= f.file_field :photo%>
  </div>

  <div class="form-group">
    <%= f.submit "Save Photo", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/photos/show.html.erb
<div class="container">
   <div class="row">
     <div class="col-lg-6">
         <%= image_tag @photo.photo.url(:large)%>
    </div>
    <div class="col-lg-6">
      <h1><%= @photo.title%></h1>
      <p><%= @photo.description%></p>
      <%= link_to "Home", root_path %>
    </div>
    
   </div>
</div>